### PR TITLE
Web Barliman

### PR DESCRIPTION
**Pull request by namin**
You can see it in action here: http://io.livecode.ch/learn/namin/Barliman

### CODE REVIEW

**Comment by webyrd** [comment]
w00t

**Comment by gregr** [comment]
@namin Wow, nice!

So this is using Scheme inside a docker container?  If really hard requests are sent, is it going to harm your site?  I'm wondering because I'll be demoing this next week, and want to make sure I don't accidentally DDoS io.livecode.ch if I link to this.

**Comment by namin** [comment]
There's a timeout of 50ms, I think. I increased it from 5ms in order to handle many Barliman requests.

**Comment by gregr** [comment]
That makes me feel better.  Thanks!

**Pull request merged**
