### PR TITLE
Try complete search if fast search fails

### PR DESCRIPTION
**Pull request by gregr**

### CODE REVIEW

**Comment by gregr** [comment]
@webyrd 
This seems to work, but let me know if I've missed anything.  I'm not too familiar with the swift code.

**Comment by webyrd** [comment]
Am I doing it right?  Synthesis seems both slow and not parsimonious.

**Comment by webyrd** [comment]
Screenshot[image: Inline image 1]

**Comment by gregr** [comment]
The screenshot didn't appear.  What query are you trying?

Note that this uses DLS for fast search, but does not make use of `conde1`, so while the full append synthesis is possible, it takes a little under a minute to finish.

query part 1

query part 2

append-complete-fallback

**Comment by webyrd** [comment]
Nevermind--I was on the wrong branch!  Thanks.

**Pull request merged**
