### PR TITLE
Promote cons in initial-env

### PR DESCRIPTION
**Pull request by gregr**
This improves the performance of some hard benchmarks by about 10x when running directly under Chez.

### CODE REVIEW

**Comment by gregr** [comment]
30s -> 3s under Chez.  About 33s -> 5s through the Barliman UI.  I guess there's a bit more overhead there.

**Comment by webyrd** [comment]
Thanks!

Can you tell if the faster system can now synthesize more of 'append'?

**Comment by gregr** [comment]
It can now synthesize a bit more than before.  This query now succeeds, guessing the argument to null?:

```
(define append
  (lambda (l s)
    (if (null? ,A) ,B ,C)))
```

While guessing the full if condition, it finds a creative cheat that gets around the gensyms:

```
(define append
  (lambda (l s)
    (if ,A ,B ,C)))
```

Best guess:
```
(define append
  (lambda (l s)
    (if _.0
      (match s
        ((quasiquote ())
          s)
        ((quasiquote ((unquote _.1)))
          (cons (car l) s))
        (_.2
          (cons (car l) (cons (car (cdr l)) _.2)))
        . _.3)
      _.4)))

Side conditions:
(num _.0)
(sym _.1 _.2)
```

Scaling it back to only guess the null? test leads to a different cheat:

```
(define append
  (lambda (l s)
    (if (,A ,D) ,B ,C)))
```

Best guess:
```
(define append
  (lambda (l s)
    (if (null? s)
      s
      (cons (car l)
        (match s
          ((quasiquote ((unquote _.0)))
            s)
          (_.1
            (cons (car (cdr l)) _.1))
          . _.2)))))

Side conditions:
(sym _.0 _.1)
```

These are all performed with the following test cases:

```
(append '() '()) ==> '()
(append `(,g1) `(,g2)) ==> `(,g1 ,g2)
(append `(,g1 ,g2) `(,g3 ,g4 ,g5)) ==> `(,g1 ,g2 ,g3 ,g4 ,g5)
```

**Comment by gregr** [comment]
The new success takes about 19s under Chez.

**Comment by webyrd** [comment]
The new success being a cheat?

I've been experimenting with using properties to help prevent
over-specialization.  In particular, the property that when l and s are
proper lists, the output must be a proper list whose length is equal to the
sum of the lengths of l and s.

I've been able to implement the property, but it is awkward to express, and
alas doesn't help prune the search.

**Comment by gregr** [comment]
No, thankfully the new success is a real one that guesses the argument to `null?`.

The rest of the queries result in cheats.  I realize I should have used different gensyms for each test case, which should better avoid cheating, but I still can't get a result after several minutes of waiting.

**Comment by webyrd** [comment]
> No, thankfully the new success is a real one that guesses the argument to
null?.

I was able to do that one before, actually, although I had to pick exactly
the right arguments.  However, I've never been able to guess the 'null?'
part, at least without using types.

**Comment by webyrd** [comment]
I'll have to try the new version with my property hack.

**Pull request merged**
